### ISSUE TITLE
Please add support for PHP 8.0+

### ISSUE THREAD

**Issue by mickel1138** [HylianShield/base32-crockford#2]
Currently this repository is restricted to use PHP 7.0+, please allow the use of PHP 8.0

**Comment by janmartenjongerius** [comment]
Feel free to make a pull request. I don't have access to anything besides my phone right now. The code should be forward compatible, so just a wider version constraint will do the trick.

**Comment by mickel1138** [comment]
Just wanted to give you an update, we have changed libraries, and no longer use this repo. 

I don't really have the time to fix this repo, there don't seem to be to many users for this repo anyway. I would suggest you archive this, unless you know of any current users.

If you wanted to fix it, here is an example of a PR: https://github.com/mickel1138/validator-base-encoding/pull/1/files
All the related repo's will have to be fixed also in the same way, a bit tricky if you want the unit tests to work.
